# Generated by Django 5.0.6 on 2024-06-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='Note',
        ),
    ]
